export default {
  ADD: 'ADD',
  EDIT: 'EDIT',
  EMPLOYEE: 'EMPLOYEE',
  MANAGER: 'MANAGER',
  ADMIN: 'ADMIN',
  PENDING: "PENDING",
  SOCKET_EMIT_EVENT_NAME_ROLE_BASED_WEB_APP: 'ROLE_BASED_WEB_APP',

  SOCKET_EMPLOYEE_UPDATE_CODE: 'E001',
  SOCKET_MANAGER_LEAVE_UPDATE_CODE: 'M001',
  SOCKET_MANAGER_TEAM_MEMBER_UPDATE_CODE: 'M002'
}